name: "[JIRA VCS] New-bug-report(Last 12h)"

on:
  schedule:
    - cron: "0 */12 * * *"      # every 12 hours
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  jira-report:
    runs-on: ubuntu-latest

    env:
      # VARIABLES
      JIRA_VCS_API_EMAIL: ${{ vars.JIRA_VCS_API_EMAIL }}
      JIRA_VCS_BUG_OPEN_ALERT_TEAM_URL: ${{ vars.JIRA_VCS_BUG_OPEN_ALERT_TEAM_URL }}
      # SECRETS
      JIRA_VCS_API_TOKEN: ${{ secrets.JIRA_VCS_API_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Jira report script (posts to Teams)
        run: python Bug-new-last-12h-teams.py
