name: 📖 Deploy GitHub Pages Using Hugo (DEV)

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop

jobs:
  create-pages:
    uses: jijeeshhomelab/Actions/.github/workflows/hugo-pages.yml@main
    secrets:
      GH_ACTIONS_TOKEN: ${{ secrets.GH_ACTIONS_TOKEN }}
    with:
      GH_BRANCH: ${{ github.ref_name }}

  deploy-pages:
    needs: create-pages
    environment:
      name: github-pages
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          ref: hugo-pages

      - uses: actions/configure-pages@v5

      - uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - id: deployment
        uses: actions/deploy-pages@v4
