name: 📖 Deploy GitHub Pages Using Hugo

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - main

jobs:
  deploy:
    uses: jijeeshhomelab/learningrepo/.github/workflows/hugo-pages.yml@main
    permissions:
      contents: write
    secrets: inherit   # <-- pass built-in GITHUB_TOKEN automatically
