name: 📖 Deploy GitHub Pages Using Hugo (DEV)

on:
  workflow_dispatch:
  push:
    branches:
      - 'develop'
      - 'dev-*'
      - 'feature/*'
      - 'main'

jobs:
  create-pages:
    uses: jijeeshhomelab/Actions/.github/workflows/hugo-pages.yml@main
    secrets:
      GH_ACTIONS_TOKEN: ${{ secrets.GH_ACTIONS_TOKEN }}
    with:
      GH_BRANCH: ${{ github.ref_name }}
