name: Reusable - Hugo Build & Deploy

on:
  workflow_call:
    inputs:
      publish_branch:
        type: string
        required: false
        default: gh-pages
    secrets:
      GH_ACTIONS_TOKEN:
        required: false

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: latest
          extended: true

      - name: Build site
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_ACTIONS_TOKEN || secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: ${{ inputs.publish_branch }}
